[package]
name = "zenoh-dissector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
epan-sys = {git="https://github.com/yuanyuyuan/wsdf", branch="PR/replace-git-submodule"}
zenoh-protocol = {git="https://github.com/eclipse-zenoh/zenoh"}
zenoh-codec = {git="https://github.com/eclipse-zenoh/zenoh"}
zenoh-buffers = {git="https://github.com/eclipse-zenoh/zenoh"}
anyhow = "1.0.75"
convert_case = "0.6.0"


[lib]
crate-type = ["cdylib"]
